BUGFIX. Get errors on `execa` package when executing the `npm run deploy` command
Error:
- Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /Applications/MAMP/htdocs/vue-users/node_modules/execa/index.js
require() of ES modules is not supported.
- Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
- Error: Cannot find module '/Applications/MAMP/htdocs/vue-users/gh-pages-deploy.js'

Reason:
- When upgrading the execa package from version 5 to version 7, errors were found due to a change in the module system used. The package now uses ECMAScript Modules (ESM) instead of CommonJS.

Solution:
- In the `gh-pages-deploy.js` file use `import` instead of `require` to add and use the packages.
- Rename the file `gh-pages-deploy.js` to `gh-pages-deploy.mjs`.
- As the file name has changed to `gh-pages-deploy.mjs`, modify it in the `deploy` npm script.

References:
- https://www.npmjs.com/package/execa
- https://www.npmjs.com/package/node-emoji
- https://stackoverflow.com/questions/43622337/using-import-fs-from-fs